export enum EnvMap {
  ENVIRONMENT = "environment",
  PORT = "port",
  LOGGER_LEVEL = "loggerLevel",
  DEBUG_PORT = "debugPort",
  URL_HOST = "urlHost",
  VERSION = "version",
  GLOBAL_PREFIX = "globalPrefix",
  MONGO_URI = "mongo.uri",
  MONGO_USERNAME = "mongo.username",
  MONGO_PASSWORD = "mongo.password",
  MONGO_PORT = "mongo.port",
  MONGO_DATABASE_NAME = "mongo.databaseName",
  MONGO_CONNECTION_ATTEMPTS = "mongo.retryAttempts",
  MONGO_CONNECTION_TIMEOUT = "mongo.connectTimeoutMS",
}
